# Generated by Django 4.2.11 on 2025-08-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_seller",
            field=models.BooleanField(default=False),
        ),
    ]
