# Generated by Django 5.2.5 on 2025-08-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("image", models.FileField(upload_to="img")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Electronics", "ELECTRONICS"),
                            ("Groceries", "GROCERIES"),
                            ("Clothings", "CLOTHINGS"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
