# Generated by Django 4.2.11 on 2025-08-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("unisex", "Unisex")],
                default="unisex",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ratings",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("t-shirts", "T-SHIRTS"),
                    ("casual shirts", "CASUAL SHIRTS"),
                    ("formal shirts", "FORMAL SHIRTS"),
                    ("jeans", "JEANS"),
                    ("formal trousers", "FORMAL TROUSERS"),
                    ("casual trousers", "CASUAL TROUSERS"),
                    ("shorts", "SHORTS"),
                    ("jackets", "JACKETS"),
                    ("sweatshirts", "SWEATSHIRTS"),
                    ("blazers", "BLAZERS"),
                    ("suits", "SUITS"),
                    ("tops", "TOPS"),
                    ("skirts", "SKIRTS"),
                    ("jeans-women", "JEANS"),
                    ("leggings", "LEGGINGS"),
                    ("kurtis", "KURTIS"),
                    ("sarees", "SAREES"),
                    ("salwar suits", "SALWAR SUITS"),
                    ("jackets-women", "JACKETS"),
                    ("sweaters", "SWEATERS"),
                    ("t-shirts-kids", "KIDS T-SHIRTS"),
                    ("shirts-kids", "KIDS SHIRTS"),
                    ("shorts-kids", "KIDS SHORTS"),
                    ("frocks", "FROCKS"),
                    ("skirts-kids", "KIDS SKIRTS"),
                    ("ethnic-wear-kids", "ETHNIC WEAR"),
                    ("sports-shoes", "SPORTS SHOES"),
                    ("casual-shoes", "CASUAL SHOES"),
                    ("formal-shoes", "FORMAL SHOES"),
                    ("boots", "BOOTS"),
                    ("heels", "HEELS"),
                    ("flats", "FLATS"),
                    ("slippers", "SLIPPERS"),
                    ("sandals", "SANDALS"),
                    ("flip-flops", "FLIP-FLOPS"),
                    ("crocs", "CROCS"),
                    ("watches", "WATCHES"),
                    ("belts", "BELTS"),
                    ("wallets", "WALLETS"),
                    ("handbags", "HANDBAGS"),
                    ("backpacks", "BACKPACKS"),
                    ("sunglasses", "SUNGLASSES"),
                    ("jewellery", "JEWELLERY"),
                    ("caps", "CAPS"),
                    ("makeup", "MAKEUP"),
                    ("skincare", "SKINCARE"),
                    ("haircare", "HAIRCARE"),
                    ("perfumes-men", "PERFUMES (MEN)"),
                    ("perfumes-women", "PERFUMES (WOMEN)"),
                    ("unisex-perfumes", "UNISEX PERFUMES"),
                ],
                max_length=50,
            ),
        ),
    ]
