# Generated by Django 4.2.11 on 2025-09-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_order_remove_product_image_product_thumbnail_review_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="disount_percentage",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="original_price",
            field=models.IntegerField(default=0),
        ),
    ]
