# Generated by Django 4.2.11 on 2025-09-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_product_price_product_discount_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="disount_percentage",
            new_name="discount_percentage",
        ),
    ]
