# Generated by Django 4.2.11 on 2025-09-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_disount_percentage_product_discount_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
