# Generated by Django 4.2.11 on 2025-09-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_product_size_product_sizes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sizes",
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[
                    ("S M L XL XXL", "S M L XL XXL"),
                    ("26 28 30 32 34 36", "26 28 30 32 34 36"),
                    ("6 7 8 9 10 11 12", "6 7 8 9 10 11 12"),
                    ("OneSize", "One Size"),
                ],
                default="M",
                max_length=20,
            ),
        ),
    ]
