# Generated by Django 4.2.11 on 2025-10-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_product_category_alter_product_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("t-shirts", "T-SHIRTS"),
                    ("casual shirts", "CASUAL SHIRTS"),
                    ("formal shirts", "FORMAL SHIRTS"),
                    ("jeans", "JEANS"),
                    ("formal trousers", "FORMAL TROUSERS"),
                    ("casual trousers", "CASUAL TROUSERS"),
                    ("shorts", "SHORTS"),
                    ("jackets", "JACKETS"),
                    ("sweatshirts", "SWEATSHIRTS"),
                    ("blazers", "BLAZERS"),
                    ("suits", "SUITS"),
                    ("tops", "TOPS"),
                    ("skirts", "SKIRTS"),
                    ("jeans", "JEANS"),
                    ("leggings", "LEGGINGS"),
                    ("kurtis", "KURTIS"),
                    ("sarees", "SAREES"),
                    ("suits", "SUITS"),
                    ("jackets", "JACKETS"),
                    ("sweaters", "SWEATERS"),
                    ("ethnic wear", "ETHNIC WEAR"),
                    ("kids t-shirts", "KIDS T-SHIRTS"),
                    ("kids shirts", "KIDS SHIRTS"),
                    ("kids shorts", "KIDS SHORTS"),
                    ("frocks", "FROCKS"),
                    ("sports shoes", "SPORTS SHOES"),
                    ("casual shoes", "CASUAL SHOES"),
                    ("formal shoes", "FORMAL SHOES"),
                    ("boots", "BOOTS"),
                    ("heels", "HEELS"),
                    ("flats", "FLATS"),
                    ("slippers", "SLIPPERS"),
                    ("sandals", "SANDALS"),
                    ("flip flops", "FLIP FLOPS"),
                    ("crocs", "CROCS"),
                    ("watches", "WATCHES"),
                    ("belts", "BELTS"),
                    ("wallets", "WALLETS"),
                    ("handbags", "HANDBAGS"),
                    ("backpacks", "BACKPACKS"),
                    ("sunglasses", "SUNGLASSES"),
                    ("jewellery", "JEWELLERY"),
                    ("caps", "CAPS"),
                    ("makeup", "MAKEUP"),
                    ("skincare", "SKINCARE"),
                    ("haircare", "HAIRCARE"),
                    ("perfumes", "PERFUMES"),
                ],
                max_length=50,
            ),
        ),
    ]
