# Generated by Django 5.2.7 on 2025-11-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_order_order_id_alter_cartitem_cart_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
