# Generated by Django 5.2.7 on 2025-11-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_size_remove_cart_created_at_cartitem_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="size",
            old_name="name",
            new_name="size",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
    ]
