# Generated by Django 5.2.7 on 2025-12-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_order_shipping_address_order_shipping_city_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="shipping_address",
            new_name="shipping_street",
        ),
    ]
