# Generated by Django 4.2.11 on 2026-01-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_rename_shipping_address_order_shipping_street"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
